import { MedicalHistoryType } from "../types";

export const emptyMedicalHistory: MedicalHistoryType = {
  pregnant: false,
  breastfeeding: false,
  diabetic: false,
  skinInfection: false,
  autoimmuneDisease: false,
  epilepsy: false,
  pacemaker: false,
  cancer: false,
  hepatitis: false,
  tattoos: false,
  permanentFillers: false,
  hypersensitiveSkin: false,
  skinDiseases: false,
  heartProblems: false,
  venerealDiseases: false,
  hormonalChanges: false,
  medication: false,
  medicationDetails: "",
  omega3: false,
  allergies: false,
  allergyDetails: "",
  anesthesiaReaction: false,
  anesthesiaReactionDetails: "",
  anaphylaxis: false,
  anaphylaxisDetails: "",
  bloodThinners: false,
  bloodThinnerDetails: "",
  hypertrophicScarring: false,
  hypertrophicScarringDetails: "",
  otherConditions: "",
  mhnotes: "",
  consentAccepted: false,
  signedAt: "",
  signatureImage: "",
};